// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddResultdetailsOKCode is the HTTP code returned for type AddResultdetailsOK
const AddResultdetailsOKCode int = 200

/*AddResultdetailsOK id

swagger:response addResultdetailsOK
*/
type AddResultdetailsOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddResultdetailsOK creates AddResultdetailsOK with default headers values
func NewAddResultdetailsOK() *AddResultdetailsOK {
	return &AddResultdetailsOK{}
}

// WithPayload adds the payload to the add resultdetails o k response
func (o *AddResultdetailsOK) WithPayload(payload string) *AddResultdetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add resultdetails o k response
func (o *AddResultdetailsOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddResultdetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// AddResultdetailsBadRequestCode is the HTTP code returned for type AddResultdetailsBadRequest
const AddResultdetailsBadRequestCode int = 400

/*AddResultdetailsBadRequest invalid input, object invalid

swagger:response addResultdetailsBadRequest
*/
type AddResultdetailsBadRequest struct {
}

// NewAddResultdetailsBadRequest creates AddResultdetailsBadRequest with default headers values
func NewAddResultdetailsBadRequest() *AddResultdetailsBadRequest {
	return &AddResultdetailsBadRequest{}
}

// WriteResponse to the client
func (o *AddResultdetailsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddResultdetailsConflictCode is the HTTP code returned for type AddResultdetailsConflict
const AddResultdetailsConflictCode int = 409

/*AddResultdetailsConflict an existing item already exists

swagger:response addResultdetailsConflict
*/
type AddResultdetailsConflict struct {
}

// NewAddResultdetailsConflict creates AddResultdetailsConflict with default headers values
func NewAddResultdetailsConflict() *AddResultdetailsConflict {
	return &AddResultdetailsConflict{}
}

// WriteResponse to the client
func (o *AddResultdetailsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
