// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddResultdetailsHandlerFunc turns a function with the right signature into a add resultdetails handler
type AddResultdetailsHandlerFunc func(AddResultdetailsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddResultdetailsHandlerFunc) Handle(params AddResultdetailsParams) middleware.Responder {
	return fn(params)
}

// AddResultdetailsHandler interface for that can handle valid add resultdetails params
type AddResultdetailsHandler interface {
	Handle(AddResultdetailsParams) middleware.Responder
}

// NewAddResultdetails creates a new http.Handler for the add resultdetails operation
func NewAddResultdetails(ctx *middleware.Context, handler AddResultdetailsHandler) *AddResultdetails {
	return &AddResultdetails{Context: ctx, Handler: handler}
}

/*AddResultdetails swagger:route POST /resultdetails addResultdetails

adds a resultdetails item

Adds a resultdetails to the system

*/
type AddResultdetails struct {
	Context *middleware.Context
	Handler AddResultdetailsHandler
}

func (o *AddResultdetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddResultdetailsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
