// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSearchableOKCode is the HTTP code returned for type GetSearchableOK
const GetSearchableOKCode int = 200

/*GetSearchableOK columns

swagger:response getSearchableOK
*/
type GetSearchableOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetSearchableOK creates GetSearchableOK with default headers values
func NewGetSearchableOK() *GetSearchableOK {
	return &GetSearchableOK{}
}

// WithPayload adds the payload to the get searchable o k response
func (o *GetSearchableOK) WithPayload(payload []string) *GetSearchableOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get searchable o k response
func (o *GetSearchableOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSearchableOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetSearchableBadRequestCode is the HTTP code returned for type GetSearchableBadRequest
const GetSearchableBadRequestCode int = 400

/*GetSearchableBadRequest bad input parameter

swagger:response getSearchableBadRequest
*/
type GetSearchableBadRequest struct {
}

// NewGetSearchableBadRequest creates GetSearchableBadRequest with default headers values
func NewGetSearchableBadRequest() *GetSearchableBadRequest {
	return &GetSearchableBadRequest{}
}

// WriteResponse to the client
func (o *GetSearchableBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
