// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUneditableHandlerFunc turns a function with the right signature into a get uneditable handler
type GetUneditableHandlerFunc func(GetUneditableParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUneditableHandlerFunc) Handle(params GetUneditableParams) middleware.Responder {
	return fn(params)
}

// GetUneditableHandler interface for that can handle valid get uneditable params
type GetUneditableHandler interface {
	Handle(GetUneditableParams) middleware.Responder
}

// NewGetUneditable creates a new http.Handler for the get uneditable operation
func NewGetUneditable(ctx *middleware.Context, handler GetUneditableHandler) *GetUneditable {
	return &GetUneditable{Context: ctx, Handler: handler}
}

/*GetUneditable swagger:route GET /uneditable getUneditable

gets columns

gets uneditable

*/
type GetUneditable struct {
	Context *middleware.Context
	Handler GetUneditableHandler
}

func (o *GetUneditable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUneditableParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
