// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LogoutOKCode is the HTTP code returned for type LogoutOK
const LogoutOKCode int = 200

/*LogoutOK OK

swagger:response logoutOK
*/
type LogoutOK struct {

	/*
	  In: Body
	*/
	Payload bool `json:"body,omitempty"`
}

// NewLogoutOK creates LogoutOK with default headers values
func NewLogoutOK() *LogoutOK {
	return &LogoutOK{}
}

// WithPayload adds the payload to the logout o k response
func (o *LogoutOK) WithPayload(payload bool) *LogoutOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout o k response
func (o *LogoutOK) SetPayload(payload bool) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// LogoutNotFoundCode is the HTTP code returned for type LogoutNotFound
const LogoutNotFoundCode int = 404

/*LogoutNotFound Sample not found

swagger:response logoutNotFound
*/
type LogoutNotFound struct {
}

// NewLogoutNotFound creates LogoutNotFound with default headers values
func NewLogoutNotFound() *LogoutNotFound {
	return &LogoutNotFound{}
}

// WriteResponse to the client
func (o *LogoutNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
