// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Jtree Metadata API
Metadata API


    Schemes:
      http
    Host: virtserver.swaggerhub.com
    BasePath: /Jtree/metadata/0.1.0
    Version: 0.1.0
    License: GPL https://www.gnu.org/licenses/gpl-3.0.en.html
    Contact: <info@distributedgenomics.ca>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
