// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Resultdetails resultdetails
// swagger:model Resultdetails
type Resultdetails struct {

	// v a f
	VAF *float32 `json:"VAF,omitempty"`

	// c nomenclature
	CNomenclature *string `json:"c_nomenclature,omitempty"`

	// coverage
	Coverage *int64 `json:"coverage,omitempty"`

	// exon
	Exon *int64 `json:"exon,omitempty"`

	// gene
	Gene *string `json:"gene,omitempty"`

	// p nomenclature
	PNomenclature *string `json:"p_nomenclature,omitempty"`

	// pcr
	Pcr *string `json:"pcr,omitempty"`

	// quality score
	QualityScore *float32 `json:"quality_score,omitempty"`

	// result
	Result *string `json:"result,omitempty"`

	// results id
	ResultsID *int64 `json:"results_id,omitempty"`

	// risk score
	RiskScore *float32 `json:"risk_score,omitempty"`

	// sample id
	SampleID *string `json:"sample_id,omitempty"`

	// uid
	UID *string `json:"uid,omitempty"`
}

// Validate validates this resultdetails
func (m *Resultdetails) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Resultdetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Resultdetails) UnmarshalBinary(b []byte) error {
	var res Resultdetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
