Select COLUMN_NAME FROM
(
SELECT    "samples" as TABLE_ONE,TABLE_NAME as TABLE_TWO ,COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE   REFERENCED_TABLE_SCHEMA = 'JTree' AND   REFERENCED_TABLE_NAME = 'samples'
UNION    
SELECT "patients" as TABLE_ONE,TABLE_NAME as TABLE_TWO ,COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE   REFERENCED_TABLE_SCHEMA = 'JTree' AND   REFERENCED_TABLE_NAME = 'patients'
UNION
SELECT "experiments" as TABLE_ONE,TABLE_NAME as TABLE_TWO ,COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE   REFERENCED_TABLE_SCHEMA = 'JTree' AND   REFERENCED_TABLE_NAME = 'experiments'
UNION
SELECT "results" as TABLE_ONE,TABLE_NAME as TABLE_TWO ,COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE   REFERENCED_TABLE_SCHEMA = 'JTree' AND   REFERENCED_TABLE_NAME = 'results'
UNION 
SELECT "resultdetails" as TABLE_ONE,TABLE_NAME as TABLE_TWO ,COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE   REFERENCED_TABLE_SCHEMA = 'JTree' AND   REFERENCED_TABLE_NAME = 'resultdetails'
) a 
WHERE (TABLE_ONE = "samples" && TABLE_TWO = "experiments") || (TABLE_ONE = "experiments" && TABLE_TWO = "samples");